services:
  miniflux-app:
    image: miniflux/miniflux:latest
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@miniflux-db/${POSTGRES_DB}?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PUID=1000
      - PGID=1000
  miniflux-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/miniflux:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.archivebox-web-redirect.redirectscheme.scheme: https
        traefik.http.services.archivebox.loadbalancer.server.port: 8080
        # Web
        traefik.http.routers.archivebox-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.archivebox-insecure.entrypoints: web
        traefik.http.routers.archivebox-insecure.service: miniflux-app
        traefik.http.routers.archivebox-insecure.middlewares: miniflux-app-web-redirect
        # Websecure
        traefik.http.routers.archivebox.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.archivebox.entrypoints: websecure
        traefik.http.routers.archivebox.service: miniflux-app
        traefik.http.routers.archivebox.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.archivebox-local-insecure.rule: Host(`miniflux-app.${LOCAL_DOMAIN}`)
        traefik.http.routers.archivebox-local-insecure.entrypoints: web
        traefik.http.routers.archivebox-local-insecure.service: miniflux-app
        traefik.http.routers.archivebox-local-insecure.middlewares: miniflux-app-web-redirect
        # Local domain secure
        traefik.http.routers.archivebox-local.rule: Host(`miniflux-app.${LOCAL_DOMAIN}`)
        traefik.http.routers.archivebox-local.entrypoints: websecure
        traefik.http.routers.archivebox-local.service: miniflux-app
        traefik.http.routers.archivebox-local.tls: true
